default: &default
  workers:
  - queues:
    - critical
    - default
    - low
    threads: <%= ENV.fetch "RAILS_MAX_THREADS" { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
